# Generated by Django 4.1.3 on 2022-12-02 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myblog',
            name='preview',
        ),
    ]
